// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TrainingHub.Data;

#nullable disable

namespace TrainingHub.Api.Migrations
{
    [DbContext(typeof(TrainingHubDbContext))]
    [Migration("20260523130000_SyncCertificateSeedData")]
    partial class SyncCertificateSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}