// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingHub.Data;

#nullable disable

namespace TrainingHub.Api.Migrations
{
    [DbContext(typeof(TrainingHubDbContext))]
    [Migration("20260520145220_Updating")]
    partial class Updating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainingHub.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Courses about software development and programming languages.",
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Courses on data analysis, machine learning and statistics.",
                            Name = "Data Science"
                        });
                });

            modelBuilder.Entity("TrainingHub.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CertificationTrackId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificationTrackId");

                    b.HasIndex("TraineeId");

                    b.ToTable("Certificates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CertificateReferenceNumber = "CERT-0001",
                            CertificationTrackId = 1,
                            IssuedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Issued",
                            TraineeId = 1
                        });
                });

            modelBuilder.Entity("TrainingHub.Models.CertificationTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("CertificationTracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Track covering front-end and back-end development.",
                            IsActive = true,
                            Name = "Full Stack Developer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Track focused on data analysis and visualization.",
                            IsActive = true,
                            Name = "Data Analyst Track"
                        });
                });

            modelBuilder.Entity("TrainingHub.Models.CertificationTrackCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificationTrackId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificationTrackId");

                    b.HasIndex("CourseId");

                    b.ToTable("CertificationTrackCourses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CertificationTrackId = 1,
                            CourseId = 1
                        },
                        new
                        {
                            Id = 2,
                            CertificationTrackId = 2,
                            CourseId = 2
                        });
                });

            modelBuilder.Entity("TrainingHub.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("HasLabComputer")
                        .HasColumnType("bit");

                    b.Property<bool>("HasProjector")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RoomCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            HasLabComputer = true,
                            HasProjector = true,
                            IsAvailable = true,
                            Location = "Building A - Room 101",
                            RoomCode = 101
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 20,
                            HasLabComputer = true,
                            HasProjector = false,
                            IsAvailable = true,
                            Location = "Building B - Lab 202",
                            RoomCode = 202
                        });
                });

            modelBuilder.Entity("TrainingHub.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DefaultCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("DurationHours")
                        .HasColumnType("float");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DefaultCapacity = 20,
                            Description = "Introductory course to C# and .NET fundamentals.",
                            DurationHours = 24.0,
                            Fee = 499.99m,
                            IsActive = true,
                            Title = "C# Fundamentals"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DefaultCapacity = 25,
                            Description = "Using Python to analyze and visualize data.",
                            DurationHours = 30.0,
                            Fee = 599.50m,
                            IsActive = true,
                            Title = "Python for Data Analysis"
                        });
                });

            modelBuilder.Entity("TrainingHub.Models.CourseSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            ClassroomId = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 25,
                            ClassroomId = 2,
                            CourseId = 2,
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 2,
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("TrainingHub.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CourseSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResultRecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseSessionId");

                    b.HasIndex("TraineeId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendanceStatus = "",
                            CourseSessionId = 1,
                            EnrolledAt = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResultStatus = "",
                            Status = "Enrolled",
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            AttendanceStatus = "",
                            CourseSessionId = 2,
                            EnrolledAt = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResultStatus = "",
                            Status = "Enrolled",
                            TraineeId = 2
                        });
                });

            modelBuilder.Entity("TrainingHub.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExpertiseArea")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Senior .NET developer and trainer.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.johnson@example.com",
                            ExpertiseArea = "Software Development",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Alice Johnson",
                            PhoneNumber = "555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Data scientist and Python instructor.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.smith@example.com",
                            ExpertiseArea = "Data Science",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Bob Smith",
                            PhoneNumber = "555-0202"
                        });
                });

            modelBuilder.Entity("TrainingHub.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TraineeId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("TraineeId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = false,
                            Message = "Welcome to TrainingHub, John!",
                            Title = "Welcome",
                            TraineeId = 1,
                            Type = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            IsRead = false,
                            Message = "You have been assigned to C# Fundamentals.",
                            Title = "Session Assigned",
                            Type = "Assignment"
                        });
                });

            modelBuilder.Entity("TrainingHub.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("TraineeId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPaid = 499.99m,
                            EnrollmentId = 1,
                            Notes = "",
                            PaidAt = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard",
                            ReferenceNumber = "PAY-1001",
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            AmountPaid = 599.50m,
                            EnrollmentId = 2,
                            Notes = "",
                            PaidAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard",
                            ReferenceNumber = "PAY-1002",
                            TraineeId = 2
                        });
                });

            modelBuilder.Entity("TrainingHub.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            IsActive = true,
                            PhoneNumber = "555-1001",
                            RegisteredAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            FullName = "Jane Smith",
                            IsActive = true,
                            PhoneNumber = "555-1002",
                            RegisteredAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TrainingHub.Models.Certificate", b =>
                {
                    b.HasOne("TrainingHub.Models.CertificationTrack", "CertificationTrack")
                        .WithMany("Certificates")
                        .HasForeignKey("CertificationTrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainingHub.Models.Trainee", "Trainee")
                        .WithMany("Certificates")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CertificationTrack");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TrainingHub.Models.CertificationTrackCourse", b =>
                {
                    b.HasOne("TrainingHub.Models.CertificationTrack", "CertificationTrack")
                        .WithMany("CertificationTrackCourses")
                        .HasForeignKey("CertificationTrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainingHub.Models.Course", "Course")
                        .WithMany("CertificationTrackCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CertificationTrack");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TrainingHub.Models.Course", b =>
                {
                    b.HasOne("TrainingHub.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TrainingHub.Models.CourseSession", b =>
                {
                    b.HasOne("TrainingHub.Models.Classroom", "Classroom")
                        .WithMany("CourseSessions")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainingHub.Models.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainingHub.Models.Instructor", "Instructor")
                        .WithMany("CourseSessions")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("TrainingHub.Models.Enrollment", b =>
                {
                    b.HasOne("TrainingHub.Models.CourseSession", "CourseSession")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainingHub.Models.Trainee", "Trainee")
                        .WithMany("Enrollments")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseSession");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TrainingHub.Models.Notification", b =>
                {
                    b.HasOne("TrainingHub.Models.Instructor", "Instructor")
                        .WithMany("Notifications")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainingHub.Models.Trainee", "Trainee")
                        .WithMany("Notifications")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Instructor");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TrainingHub.Models.Payment", b =>
                {
                    b.HasOne("TrainingHub.Models.Enrollment", "Enrollment")
                        .WithMany("Payments")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainingHub.Models.Trainee", "Trainee")
                        .WithMany("Payments")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TrainingHub.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("TrainingHub.Models.CertificationTrack", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("CertificationTrackCourses");
                });

            modelBuilder.Entity("TrainingHub.Models.Classroom", b =>
                {
                    b.Navigation("CourseSessions");
                });

            modelBuilder.Entity("TrainingHub.Models.Course", b =>
                {
                    b.Navigation("CertificationTrackCourses");

                    b.Navigation("CourseSessions");
                });

            modelBuilder.Entity("TrainingHub.Models.CourseSession", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("TrainingHub.Models.Enrollment", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TrainingHub.Models.Instructor", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("TrainingHub.Models.Trainee", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Enrollments");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
